[package]
name = "mxselfbot"
version = "0.0.0"
authors = ["0x1a8510f2 <admin@0x1a8510f2.space>"]
edition = "2018"

# Deps

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "6b600d7e6db8fb2b8fa28e476b47dae8fb411221"
default-features = true
features = ["encryption", "markdown"]

[dependencies.signal-hook]
version = "0.3.8"
features = ["extended-siginfo"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.url]
version = "2"

[dependencies.lazy_static]
version = "1"